### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Robo-DD** [ScheiklP/movement-primitive-diffusion#2]
When I run python scripts/train.py --config-name dummy +experiments/obstacle_avoidance=train_prodmp_transformer,error executing job with overrides: ['+experiments/obstacle_avoidance=train_prodmp_transformer']. And why  the dummy.yaml is empty?

**Comment by ScheiklP** [comment]
Hi @dsyup ,
this is probably fixed now through https://github.com/ScheiklP/movement-primitive-diffusion/pull/3.
Could you pull and try again?

dummy.yaml is empty to have an empty base config for hydra that can be used to freely override and add new parameters.

**Comment by Robo-DD** [comment]
Thank you so much for your help! Your suggestions worked, and the issue is now resolved.
